[groups]
names = [ "₁", "₂", "3", "4", "5", "6", "7", "8", "₉" ]

[groups.shortcuts]
azerty = [ 'ampersand', 'eacute', 'quotedbl', 'apostrophe', 'parenleft', 'minus', 'egrave', 'underscore', 'ccedilla' ]
qwerty = [ '1', '2', '3', '4', '5', '6', '7', '8', '9' ]

[scratch.term]
x = 0.1
y = 0
width = 0.8
height = 0.4
opacity = 1

[scratch.files]
x = 0.25
y = 0.25
width = 0.5
height = 0.5
opacity = 1

[layout.colors]
normal = "#212121"
focus = "#BB9AF7"

[layout.mtall]
margin = 8
ratio = 0.6
max_ratio = 0.8
min_ratio = 0.2

[bar.colors]
fallback = "#212121"
apps = "#BB9AF7"
exit = "#F7768E"
this = "#565F89"
other = "#FF9E64"
urgent = "#F7768E"

[bar.colors.background]
normal = "#1A1B26"
bright = "#d5d6db"

[bar.colors.foreground]
normal = "#9699A3"
bright = "#CFC9C2"
dark = "#202734"

[bar.main]
height = 30

[bar.main.gbox]
padding = 2

[bar.main.gbox.font]
size = 16
normal = "Hack Nerd Font Mono"

[bar.main.font]
size = 16
normal = "Hack Nerd Font Mono"
bold = "Hack Nerd Font Mono Bold"

[bar.secondary]
height = 26

[bar.secondary.gbox]
padding = 2

[bar.secondary.font]
size = 14
normal = "Hack Nerd Font"
bold = "Hack Nerd Font Bold"
