[groups]
names = [ "www", "irc", "dev", "dev.", "term", "log", "sys", "misc", "mov" ]

[groups.shortcuts]
azerty = [ 'ampersand', 'eacute', 'quotedbl', 'apostrophe', 'parenleft', 'minus', 'egrave', 'underscore', 'ccedilla' ]
qwerty = [ '1', '2', '3', '4', '5', '6', '7', '8', '9' ]

[scratch.term]
width = 0.8
height = 0.6
opacity = 0.8

[layout.colors]
normal = "#212121"
focus = "#1A73E8"

[layout.mtall]
margin = 8
ratio = 0.6
max_ratio = 0.8
min_ratio = 0.2

[bar.colors]
fallback = "#212121"
apps = "#1A73E8"
exit = "#E53935"
this = "#1A73E8"
other = "#F57C00"
urgent = "#E53935"

[bar.colors.background]
normal = "#212121"
bright = "#3D3D3D"

[bar.colors.foreground]
normal = "#969696"
bright = "#E6E6E6"
dark = "#212121"

[bar.main]
height = 26

[bar.main.gbox]
padding = 4

[bar.main.font]
size = 14
normal = "Hack Nerd Font"
bold = "Hack Nerd Font Bold"

[bar.secondary]
height = 26

[bar.secondary.gbox]
padding = 4

[bar.secondary.font]
size = 14
normal = "Hack Nerd Font"
bold = "Hack Nerd Font Bold"